### PR TITLE
Add memory_size function

### PR DESCRIPTION
**Pull request by crackcomm**

### CODE REVIEW

**Comment by kayceesrk** [comment]
Thanks for the PR. 

In order to review this PR, it would be useful to know what the motivation is to add this one function but not all of the others that are missing. Is this function the only function needed to do something useful or is the plan to add more missing functions?

You should remove the cached file that’s been added as a mistake: _esy/hdr_histogram/cache/project-0d9d711bb37c48099e2ba56f57b39a63

**Comment by crackcomm** [comment]
Thanks for the catch.

It was a function I needed but I might add more missing functions.

**Comment by kayceesrk** [comment]
Thanks. I’ll merge this one. The other functions may be added later. 

The return type of the new function is `int64`. For the other functions, we cast the result to an `int`. I made this choice for two reasons. First to avoid the allocations associated with manipulation of `int64` values in OCaml. The other to be able to make it easier to use the API (using OCaml `int` rather then `int64`). For consistency of the API, we have to choose one of them uniformly. @sadiqj what do you think?

**Comment by crackcomm** [comment]
Thanks.

I think `int` in fact should work just fine for histogram memory size.

**Comment by sadiqj** [comment]
I'm in favour of `int` and just not supporting 32-bit platforms.

**Pull request merged**
